name: Linter

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cpp-linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: 16 # Clang version
          style: file # Use .clang-format
          tidy-checks: '' # Use .clang-tidy
          # Only update a single comment in PR threads
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}

      - name: Fail fast
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # When stable for deployment,
        # run: exit 1